<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RailRouteHelper.Protocol</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RailRouteHelper.Core/RailRouteHelper.Core.csproj" />
    <ProjectReference Include="../RailRouteHelper.Operations/RailRouteHelper.Operations.csproj" />
  </ItemGroup>
</Project>
