<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>RailRouteHelper.Web.Tests</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/RailRouteHelper.LiveOperations/RailRouteHelper.LiveOperations.csproj" />
    <ProjectReference Include="../../src/RailRouteHelper.Operations/RailRouteHelper.Operations.csproj" />
    <ProjectReference Include="../../src/RailRouteHelper.Protocol/RailRouteHelper.Protocol.csproj" />
    <ProjectReference Include="../../src/RailRouteHelper.Web/RailRouteHelper.Web.csproj" />
  </ItemGroup>
</Project>
