<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>RailRouteHelper.Monitoring.Tests</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RailRouteHelper.Monitoring/RailRouteHelper.Monitoring.csproj" />
    <ProjectReference Include="../../src/RailRouteHelper.Operations/RailRouteHelper.Operations.csproj" />
    <ProjectReference Include="../../src/RailRouteHelper.Protocol/RailRouteHelper.Protocol.csproj" />
    <ProjectReference Include="../../src/RailRouteHelper.Replay/RailRouteHelper.Replay.csproj" />
  </ItemGroup>
</Project>
