<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RailRouteHelper.SaveSchema</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RailRouteHelper.Core/RailRouteHelper.Core.csproj" />
    <ProjectReference Include="../RailRouteHelper.SaveFiles/RailRouteHelper.SaveFiles.csproj" />
  </ItemGroup>
</Project>
