<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RailRouteHelper.Monitoring</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RailRouteHelper.Operations/RailRouteHelper.Operations.csproj" />
    <ProjectReference Include="../RailRouteHelper.Protocol/RailRouteHelper.Protocol.csproj" />
    <ProjectReference Include="../RailRouteHelper.SaveFiles/RailRouteHelper.SaveFiles.csproj" />
    <ProjectReference Include="../RailRouteHelper.SaveSchema/RailRouteHelper.SaveSchema.csproj" />
  </ItemGroup>
</Project>
